[package]
name = "ethereum-tx-sign"
version = "1.0.0"
description = "Allows you to model a raw ethereum transaction and sign it with your private key"
repository = "https://github.com/synlestidae/ethereum-tx-sign"
license = "MIT"
keywords = ["web3", "ethereum", "transaction", "sign"]
authors = ["Mate Antunovic <mateATantunovic.nz>"]
readme = "README.md"

[dependencies]
ethereum-types = "0.4"
serde = "1.0"
serde_derive = "1.0"
serde_json = "1.0"
tiny-keccak="1.4.2"
rlp = "0.2.2"
